### ISSUE TITLE
Requesting access to the rust version.

### ISSUE THREAD

**Issue by Intege-rs** [cea-sec/miasm#1513]
Sorry for making an issue for this but I don't know how to formally contact you guys. Would it be possible to get access to the rust version of miasm?

**Comment by immortalp0ny** [comment]
Hi! The same question. I would like to test miasm-rs if possible.

**Comment by mrexodia** [comment]
Same here!

**Comment by serpilliere** [comment]
Hi all!

We have in mind to switch the project to public instead.
Keep in mind that it will be in its current state, no more, no less.

**Comment by serpilliere** [comment]
Hi!
I received the permission to switch the repo to public this week.
I will update the project to make it compile & run (with upadted crates).
Once it's done, I will make the switch.

**Comment by Intege-rs** [comment]
Any news on making the repo public?

**Comment by serpilliere** [comment]
With some luck, for Christmas!

**Comment by serpilliere** [comment]
Some news here: The update of the code is nearly finished.
After this, I will do some more tests and we should be ok for a release! 🎁

**Comment by yujack008** [comment]
> Some news here: The update of the code is nearly finished. After this, I will do some more tests and we should be ok for a release! 🎁

i lile rust version，can run on android and ios?

**Comment by serpilliere** [comment]
Little update: some modules make the rust code segfault (yes, segfault...)
I will fix this and release as I will be very glad to have some help from the community 😄

**Comment by Intege-rs** [comment]
Any Updates? <3

**Comment by serpilliere** [comment]
Yes!
@Redhpm has updated the rust part, and bumped about 140 versions of llvm (from 80 to 220 if I remember correctly!) and it works with python 3.13 
So first of all, thanks a lot @Redhpm !
He also told me that there is a segfault using 3.14 (the 𝜋 version of python?!)

**Comment by Redhpm** [comment]
I'll see when I have time if updating more stuff (most importantly Pyo3 which makes the bindings) fixes the python 3.14 segfaults. The project does need some reanimation because it has not been touched for a bit now, so it seems reasonable to hope the issue lies here. This will require a bit of work since a lot of APIs have changed in Pyo3 since then.
If that's enough to fix the obvious crashes, I think it will be in a "releasable state".

**Comment by Redhpm** [comment]
Hi !
Some news: I was able to fix the issues, so far I tested on:
- 3.11
- 3.12
- 3.13
- 3.14

And pretty much everything works as expected now.

**Comment by mrexodia** [comment]
Will the rust port eventually be in this repository or will there be a separate `miasm-rs` repository? I'm asking because the maintenance of this repository is somewhat limited, but I opened some PRs to modernize the python setup and fix some memory issues. I think @mrphrazer also has a fork. If you are open to it, I think we are both happy to take on some maintenance tasks of the Python version.

**Comment by Redhpm** [comment]
Hi, here is an overview just to make sure we are on the same page:

- `miasm-rs`, a rust crate that implements pure rust objects, as well as proxy objects in order to create an "extension module" for python. this crate does not implement everything from the original miasm.
- `miasm`, a python module, which currently is in this repo:  pure python + C for the jitter.
- another `miasm` (a fork of this repo, available here: https://github.com/serpilliere/miasm/tree/rust_version ), the same python module, but that uses miasm-rs for some chosen objects. For instance: Expressions, instead of being defined in python, the miasm.expression.expresion file will import from miasm-rs (and so on for disas, lifting, jitting etc... things you want to be _quick_).
  I rebased the fork locally, it will need to be published too.

That means there are 3 ways to go:
- Maintain a separate pure python miasm (this repo), and use the modified version only when using miasm-rs
- Make the current miasm always depend on miasm-rs
- A sort of mix where you try to import `miasm-rs`, if it fails you fall back on python.

In **all cases**, the PRs you did are useful, so they should be merged in my opinion. For instance, migrating the python module to `pyproject.toml` will be kept in all cases. If both projects are kept distinct, the patch can be rebased on the fork, if both are fused (as it touches something not modified by the existence of miasm-rs), it will stay etc.

For the maintenance part, the project is slowly (but surely !) being worked on again.
We'll see exactly how we want everything to go, but one thing is for sure: I'll be taking more and more time concerning both this repo and miasm-rs. It is currently very much a **side thing** for me, but it will become more prevalent in the next months/years.

In conclusion: still a lot of stuff to define, but it will happen eventually. 

PS (@serpilliere): if you think of something to add to that, please do :)
